### ISSUE TITLE
No definition for 'data'

### ISSUE THREAD

**Issue by dgarner-cg** [Corsinvest/cv4pve-admin#101]
### Bug type

Component

### Component name

Autosnap

### What happened?

Tried using Snapshot

### Expected behavior

Back up files

### Relevant log output

```shell
2024-04-06 07:41:20.129 -05:00 [ERR] 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'   <s:Corsinvest.ProxmoxVE.AutoSnap.Api.Application>
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'
```

### Proxmox VE Version

8.1

### Version (bug)

1.1.0

### What browsers are you seeing the problem on?

Firefox

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
Can you specify what you are doing?

**Comment by franklupo** [comment]
News?
