### ISSUE TITLE
Docker image 1.1.0 wont start

### ISSUE THREAD

**Issue by sachz19** [Corsinvest/cv4pve-admin#103]
### Bug type

Other

### Component name

Docker

### What happened?

Following the steps for preparing docker, i created the folder and file like mentioned in the documentation.
The container starts up and stops immediately. 

### Expected behavior

That the container would start.

### Relevant log output

```shell
text  error  warn  system  array  login  

The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'Corsinvest.ProxmoxVE.Admin.dll' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

** Press ANY KEY to close this window **
```

### Proxmox VE Version

8.0

### Version (bug)

1.1.0

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
What system did you run it on?

**Comment by sachz19** [comment]
Tried it on Unraid 6.12.10 (based on slackware)
But trying to run it based on the latest docker container 1.1.0

**Comment by franklupo** [comment]
can you try on a linux machine like debian?

**Comment by sachz19** [comment]
just tried it on ubuntu server, it works.
Are there specific dependencies that i need to take into account if I want to run this on Unraid?

**Comment by franklupo** [comment]
News?
