### ISSUE TITLE
Couldn't authenticate user: missing Two Factor Authentication (TFA)

### ISSUE THREAD

**Issue by onlineapps-cloud** [Corsinvest/cv4pve-admin#111]
### Bug type

Other

### What happened?

hi, i have PVE with 2fa enabled, but on configuration stage i cannot find where to put 2fa, when i want to go next, i get this error: Couldn't authenticate user: missing Two Factor Authentication (TFA)
![image](https://github.com/user-attachments/assets/9ecfb799-6119-444d-9ef5-de2ff2232dbb)

### Expected behavior

i expect to put 2fa base32 key to automatic generate 2fa code or get modal window with prompt to enter 2fa code.

### Proxmox VE Version

8.2.4

### Version (bug)

1.1.2

### What browsers are you seeing the problem on?

Firefox

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
2fa is not for this case. use a user without 2fa or api token

Best regards

**Comment by onlineapps-cloud** [comment]
ok, please help me in one moment, to give permission to API token, i generated api token, but i get error: Permission check failed (/, Sys.Audit)
i checked that my API token don't have any permission, but i don't know how to give permission to my token
![image](https://github.com/user-attachments/assets/f575dbc0-a825-438b-9a3e-b5617b61c5a1)
bu my user have all permissions
![image](https://github.com/user-attachments/assets/2806c5e1-668b-4a84-8cc2-5272df912b88)

**Comment by onlineapps-cloud** [comment]
i put api token in this format:  `root@pam!test=fb0acc61-0c2f-4fec-...`
