### ISSUE TITLE
cannot add user

### ISSUE THREAD

**Issue by tradeitsolutions** [Corsinvest/cv4pve-admin#112]
### Bug type

Component, Docs (cv4pve-admin)

### What happened?

hi, i'm using docker version of cv4pve-admin connected with a cluster of proxmox ve 8.2.
My only problem is that i cannot add user other than the default admin@local.
![error2](https://github.com/user-attachments/assets/ab2c0334-ab2e-4c70-a926-00aa774da01b)
![error2](https://github.com/user-attachments/assets/cb84bde1-4cbd-435b-a091-7df64c127a4c)

### Expected behavior

i'd like to add new users for audit

### Proxmox VE Version

8.2.4

### Version (bug)

1.1.2

### Version (working)

1.1.2

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
We are checking the problem

Best reagrds

**Comment by zandhaas** [comment]
I have the same issue and I tried Edge and firefox
