### ISSUE TITLE
VM Auto Snapshot Selection

### ISSUE THREAD

**Issue by gsaudade99** [Corsinvest/cv4pve-admin#116]
### Feature request type

Enhance component

### Component name

Auto Snapshot

### Is your feature request related to a problem?

It would be really helpfull to be able to choose all vms **except** some vm. In my case I want to be hable to snapshot all vm's except 4 of them. I have about 100 proxmox vms and it's teadeous to click on each one of them.

### Describe the solution you'd like

Have a button / featured / segment where I could select all expect some.

### Have you seen this feature anywhere else?

In Proxmox VM backup selection for example.

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
Hi,
add `@all` and prefix minus for other VM.

`@all,-12,-345,-namevm,-namejolly*`

**Comment by gsaudade99** [comment]
Hello, 
thanks mate!

Btw, is the deduplication an UI VM IDs a bug? (shown on the first picture) 

 ![image](https://github.com/user-attachments/assets/99f9b389-f527-4cd4-9c35-ac9d0b466758)
  
  
![image](https://github.com/user-attachments/assets/830a10c2-aaa2-4c04-a1e0-805be9fc7441)
