### ISSUE TITLE
Docker said: latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by gilbertoferreira** [Corsinvest/cv4pve-admin#37]
### Bug type

Other

### What happened?

Tried to used the docker but got error

### Expected behavior

Expected to get the app up and running. 

### Relevant log output

```shell
docker pull corsinvest/cv4pve-admin
Using default tag: latest
Error response from daemon: manifest for corsinvest/cv4pve-admin:latest not found: manifest unknown: manifest unknown
```

### Proxmox VE Version

7

### Version (bug)

v0.0.7-beta

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gilbertoferreira** [comment]
Yes but how?

**Comment by franklupo** [comment]
> Yes but how?

docker pull corsinvest/cv4pve-admin:1.0.0-rc.1

**Comment by gilbertoferreira** [comment]
mkdir -p /DockerData/cv4pve-admin/
touch  /DockerData/cv4pve-admin/appsettings.json

docker run -d -p 5000:5000 -e TZ=America/Sao_Paulo -v /DockerData/cv4pve-admin/data:/app/data -v /DockerData/cv4pve-admin/appsettings.json:/app/appsettings.json corsinvest/cv4pve-admin:1.0.0-rc.1 
47325d03b08c1edc0e8a83a65506726496f42a33f5846440d087b23cc1bca73c
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/DockerData/cv4pve-admin/appsettings.json" to rootfs at "/app/appsettings.json": mount /DockerData/cv4pve-admin/appsettings.json:/app/appsettings.json (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by franklupo** [comment]
you created the file /DockerData/cv4pve-admin/appsettings.json?
