### ISSUE TITLE
PVE Autentication with ApiToken not work : 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'

### ISSUE THREAD

**Issue by ChWeiler** [Corsinvest/cv4pve-admin#4]
cv4pve-admin:0.0.4-beta
- start Docker
- login with default user and password
- Fast configuration starts
- enter "Proxmox VE Web Api Login" and "Proxmox VE SSH Login"
- enter a "Proxmox VE Nodes"

When i push next button comes the error message.

It´s a linux Debain 11 in an unprivileged Proxmox Container with nesting.
The same happens in the privileged Container

**Comment by franklupo** [comment]
ProxmoxVe versìon?

**Comment by ChWeiler** [comment]
root@pve:~# pveversion --verbose
proxmox-ve: 7.4-1 (running kernel: 6.2.9-1-pve)
pve-manager: 7.4-3 (running version: 7.4-3/9002ab8a)
pve-kernel-6.2: 7.4-1
pve-kernel-5.15: 7.3-3
pve-kernel-5.13: 7.1-9
pve-kernel-6.2.9-1-pve: 6.2.9-1
pve-kernel-6.2.6-1-pve: 6.2.6-1
pve-kernel-5.0: 6.0-11
pve-kernel-5.15.102-1-pve: 5.15.102-1
pve-kernel-5.15.74-1-pve: 5.15.74-1
pve-kernel-5.15.64-1-pve: 5.15.64-1
pve-kernel-5.13.19-6-pve: 5.13.19-15
pve-kernel-5.13.19-1-pve: 5.13.19-3
pve-kernel-5.0.21-5-pve: 5.0.21-10
pve-kernel-5.0.15-1-pve: 5.0.15-1
ceph-fuse: 15.2.17-pve1
corosync: 3.1.7-pve1
criu: 3.15-1+pve-1
glusterfs-client: 9.2-1
ifupdown: residual config
ifupdown2: 3.1.0-1+pmx3
ksm-control-daemon: 1.4-1
libjs-extjs: 7.0.0-1
libknet1: 1.24-pve2
libproxmox-acme-perl: 1.4.4
libproxmox-backup-qemu0: 1.3.1-1
libproxmox-rs-perl: 0.2.1
libpve-access-control: 7.4-2
libpve-apiclient-perl: 3.2-1
libpve-common-perl: 7.3-3
libpve-guest-common-perl: 4.2-4
libpve-http-server-perl: 4.2-1
libpve-rs-perl: 0.7.5
libpve-storage-perl: 7.4-2
libqb0: 1.0.5-1
libspice-server1: 0.14.3-2.1
lvm2: 2.03.11-2.1
lxc-pve: 5.0.2-2
lxcfs: 5.0.3-pve1
novnc-pve: 1.4.0-1
proxmox-backup-client: 2.3.3-1
proxmox-backup-file-restore: 2.3.3-1
proxmox-kernel-helper: 7.4-1
proxmox-mail-forward: 0.1.1-1
proxmox-mini-journalreader: 1.3-1
proxmox-offline-mirror-helper: 0.5.1-1
proxmox-widget-toolkit: 3.6.3
pve-cluster: 7.3-3
pve-container: 4.4-3
pve-docs: 7.4-2
pve-edk2-firmware: 3.20221111-2
pve-firewall: 4.3-1
pve-firmware: 3.6-4
pve-ha-manager: 3.6.0
pve-i18n: 2.11-1
pve-qemu-kvm: 7.2.0-8
pve-xtermjs: 4.16.0-1
qemu-server: 7.4-2
smartmontools: 7.2-pve3
spiceterm: 3.2-2
swtpm: 0.8.0~bpo11+3
vncterm: 1.7-1
zfsutils-linux: 2.1.9-pve1

**Comment by franklupo** [comment]
the data/logs directory contains the logs.
Can you attach files and database?

Best regards

**Comment by ChWeiler** [comment]
I tested it with 
- binary repository
- Synology Docker
Always the same error.

**Comment by pandel** [comment]
Try using root@pam as the Proxmox Cluster user and remove API token, if given. That helped, at least for me.

**Comment by ChWeiler** [comment]
I had enter the Username, Password and **API-Token**. That dosn't work.
**With Username root@pam and password it works find.**

**Comment by franklupo** [comment]
Hi,
i split autentication APi with 2 modal:
- crdential
- Api Token

Api Token has a problem that I am correcting

best regards
