### ISSUE TITLE
Disgnostic export pdf

### ISSUE THREAD

**Issue by matteocv** [Corsinvest/cv4pve-admin#42]
### Bug type

Component

### Component name

DIAGNOSTIC

### What happened?

![MicrosoftTeams-image (3)](https://github.com/Corsinvest/cv4pve-admin/assets/130752176/7fd74531-be31-4d42-9f3b-229a4a710730)

### Expected behavior

PDF OUTPUT

### Proxmox VE Version

6.4

### Version (bug)

1.0.0-rc.1

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [X] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
The problem is for Linux/Mac and is the missing libSkiaSharp library.
