### ISSUE TITLE
CV4PVE-ADMIN Install on CentOS 8

### ISSUE THREAD

**Issue by kenrmayfield** [Corsinvest/cv4pve-admin#66]
I installed CV4PVE-ADMIN on CentOS 8.  However the Install is not working.  I did use the Linux Instruction from the Guide CV4PVE-ADMIN v1.0.0-rc.3. 

On the Services for CV4PVE-ADMIN I receive the Errors:
1. cv4pve-admin.service: Failed to determine user credentials: No such process
2. cv4pve-admin.service: Failed at step USER spawning /home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin: No
    such process
3. cv4pve-admin.service: Main process exited, code=exited, status=217/USER
4. cv4pve-admin.service: Failed with result 'exit-code'.

**This is the Code I used to Install:**
wget https://github.com/Corsinvest/cv4pve-admin/releases/download/vXX.XX.XX/cv4pve-admin-linux-x64.zip
unzip /home/cv4pve-admin-linux-x64.zip -d /home/cv4pve-admin
chmod 777 /home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin
chmod -R 0755 /home/cv4pve-admin/wwwroot

Use vi Editor to Edit:
/etc/systemd/system/cv4pve-admin.service

[Unit]
Description=cv4pve-admin Web Application
[Service]
WorkingDirectory=/home/cv4pve-admin
ExecStart=/home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin
Restart=always
RestartSec=10
SyslogIdentifier=cv4pve-admin
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
[Install]
WantedBy=multi-user.target

Start the Service:
systemctl enable cv4pve-admin.service
systemctl start cv4pve-admin.service

I also tried with the Original VAR variables from the Guide however it is the same Errors.

Also,  will CV4PVE-ADMIN install on FreeBSD?

Thanks,

Kenneth

**Comment by franklupo** [comment]
Does the software work if done manually?

best regards

**Comment by kenrmayfield** [comment]
Frank,

What do you mean by Done Manually?  Can you please Explain?

Is the Code that I Sent in the Previous Posting Correct?

Also, will CV4PVE-ADMIN install on FreeBSD?


Thanks,
Kenneth

**Comment by franklupo** [comment]
If you try to run it from shell does it work?
Yes, the creation of service in Ubuntu or Debian is correct.

**Comment by kenrmayfield** [comment]
Yes I did Run from the Shell.  My Original First Message was done with the Shell.  It does not work.  I am using CentOS 8
from Shell.

Also, will CV4PVE-ADMIN install on FreeBSD?

**Comment by matteocv** [comment]
Hello @kenrmayfield,

Could you try to go inside `/home/cv4pve-admin` and run `./Corsinvest.ProxmoxVE.Admin` ?

Do you get an error?

**Comment by matteocv** [comment]
Hello @kenrmayfield,
did you tried?

**Comment by kenrmayfield** [comment]
Matteo,

I have not tried just yet.   I will today.

Kenneth

On 2023-07-06 2:47 am, Matteo Botta wrote:

> Hello @kenrmayfield [1],
> did you tried?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/kenrmayfield
[2] 
https://github.com/Corsinvest/cv4pve-admin/issues/66#issuecomment-1623156773
[3]

**Comment by kenrmayfield** [comment]
Matteo,

**The Services will not Run:**
[root@localhost /]# systemctl status cv4pve-admin
● cv4pve-admin.service - cv4pve-admin Web Application
   Loaded: loaded (/etc/systemd/system/cv4pve-admin.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (thawing) (Result: exit-code) since Thu 2023-07-06 21:14:40 EDT; 4s ago
  Process: 5346 ExecStart=/var/cv4pve-admin/Corsinvest.ProxmoxVE.Admin (code=exited, status=217/USER)
 Main PID: 5346 (code=exited, status=217/USER)

Since the Services will not run,  I did not try to run ./Corsinvest.ProxmoxVE.Admin.


Kenneth

**Comment by franklupo** [comment]
manually it works. Open port 5000.

let's investigate why services on centos give problems

**Comment by weili0677** [comment]
cv4pve-admin[542812]: Default extraction directory [/var/www] either doesn't exist or is not accessible for read/write.

**Comment by franklupo** [comment]
The problem was https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization
set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 and try

best regards

**Comment by franklupo** [comment]
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0

**Comment by franklupo** [comment]
I test "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0" on CentOS 8 and work.

**Comment by kenrmayfield** [comment]
Frank,

Ok.

I have no idea were this Settings needs to be placed?

On 2023-08-16 10:18 am, Daniele Corsini wrote:

> I test "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0" on CentOS 8 and 
> work.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Corsinvest/cv4pve-admin/issues/66#issuecomment-1680811478
[2]

**Comment by franklupo** [comment]
In service or shell

**Comment by kenrmayfield** [comment]
Frank,

I should have been more Detailed.

How do you Add to the Service or Shell?  What would the Syntax look 
like?

On 2023-08-16 5:50 pm, Daniele Corsini wrote:

> In service or shell
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Corsinvest/cv4pve-admin/issues/66#issuecomment-1681367150
[2]

**Comment by kenrmayfield** [comment]
Frank,

I should have been more Detailed.

How do you Add to the Service?

I guess by the Shell part you mention,  I would have to Run export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 at the Shell before I Run ./Corsinvest.ProxmoxVE.Admin..........Right?

**My Journal Logs show:**
Aug 16 18:41:09 localhost.localdomain systemd[4099]: cv4pve-admin.service: Failed to determine user credentials: No such process
Aug 16 18:41:09 localhost.localdomain systemd[4099]: cv4pve-admin.service: Failed at step USER spawning /home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin: No such process
Aug 16 18:41:09 localhost.localdomain systemd[1]: cv4pve-admin.service: Main process exited, code=exited, status=217/USER
Aug 16 18:41:09 localhost.localdomain systemd[1]: cv4pve-admin.service: Failed with result 'exit-code'.


I did run export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0  at the Shell and then Ran ./Corsinvest.ProxmoxVE.Admin and **the Error is the same.**

==================================================================
**I did also try and Add export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to the /etc/skel/.bashrc as:**
######## .bashrc

######## Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

######## User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
**export PATH**
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
######## Uncomment the following line if you don't like systemctl's auto-paging feature: 
######## export SYSTEMD_PAGER=

######## User specific aliases and functions 

=========================================================================

**The Error still the same.**

**Comment by franklupo** [comment]
add `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0` in service file

**Comment by kenrmayfield** [comment]
@franklupo 

Do you mean Add it too the RC.CONF File?

**Comment by franklupo** [comment]
cv4pve-admin.service

**Comment by kenrmayfield** [comment]
**Still same Error.**

**I have Added DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to:**
/etc/systemd/system/cv4pve-admin.service


**This is what My Service File for cv4pve-admin.service looks like with DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 added:**
[Unit]
Description=cv4pve-admin Web Application

[Service]
WorkingDirectory=/home/cv4pve-admin
ExecStart=/home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin
Restart=always
RestartSec=10
SyslogIdentifier=cv4pve-admin
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
[Install]
WantedBy=multi-user.target

**Comment by kenrmayfield** [comment]
@franklupo
@matteocv 

**I still Receive the Same Errors that listed are on My Comments from July 6.**

Running CV4PVE-ADMIN on CentOS 8 Stream.

**I have Added DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to:**
/etc/systemd/system/cv4pve-admin.service

**This is what My Service File for cv4pve-admin.service looks like with DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 added to the Service File:**
[Unit]
Description=cv4pve-admin Web Application

[Service]
WorkingDirectory=/home/cv4pve-admin
ExecStart=/home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin
Restart=always
RestartSec=10
SyslogIdentifier=cv4pve-admin
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
[Install]
WantedBy=multi-user.target

**Comment by franklupo** [comment]
Does using Debian or another distribution work?

have you tried using docker?

**Comment by kenrmayfield** [comment]
@franklupo
@matteocv

**Does everything look correct?**

==================================================================
**BASHRC File :**

I did also try and Add export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to the /etc/skel/.bashrc as:
######## .bashrc

######## Source global definitions
if [ -f /etc/bashrc ]; then
. /etc/bashrc
fi

######## User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
######## Uncomment the following line if you don't like systemctl's auto-paging feature:
######## export SYSTEMD_PAGER=

######## User specific aliases and functions

=========================================================================
**SERVICE File:**

I have Added DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 to:
/etc/systemd/system/cv4pve-admin.service

This is what My Service File for cv4pve-admin.service looks like with DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 added:
[Unit]
Description=cv4pve-admin Web Application

[Service]
WorkingDirectory=/home/cv4pve-admin
ExecStart=/home/cv4pve-admin/Corsinvest.ProxmoxVE.Admin
Restart=always
RestartSec=10
SyslogIdentifier=cv4pve-admin
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
[Install]
WantedBy=multi-user.target
