### ISSUE TITLE
net7.0 does not exist

### ISSUE THREAD

**Issue by Diego77648** [Corsinvest/cv4pve-admin#70]
### Bug type

Component

### Component name

Net7.0

### What happened?

I have Net7.0 installed but visual studio says I dont

### Expected behavior

.

### Proxmox VE Version

7.3.6

### Version (bug)

v1.0.0-rc.3

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenrmayfield** [comment]
Visual Studio 2022 must be greater or equal too 17.5 to support .NET 7.0.

or 


1.  Close Visual Studio and any Visual Studio Apps running 
2.  Go to your Advanced System Settings --> Advanced --> Environment Variables
3.  Under System Variables change the "Path" too C:\Program Files(x86)\dotnet
4.  Move the "C:\Program Files\dotnet" too "C:\Program Files(x86)\dotnet"
5.  Press OK and Restart
