### ISSUE TITLE
Install on the PVE host will let PVE web can't access

### ISSUE THREAD

**Issue by weili0677** [Corsinvest/cv4pve-admin#74]
### Bug type

Other

### What happened?

1、install cv4pve-admin on PVE host
2、open PVE website(8006 port)
3、open cv4pve-admin(5000 port) and login.
4、refresh PVE website will get connect fail error.

If I use another browser will open PVE website success.when I restart browser and only access PVE website it is good.

### Expected behavior

fix this bugs.

### Proxmox VE Version

8.0.3

### Version (bug)

1.0.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
could it be a cache problem?

**Comment by weili0677** [comment]
> could it be a cache problem?

I don't know. May be because I set the WEB API with linux "root" account？

**Comment by kenrmayfield** [comment]
@weili0677 

The Proxmox Connect Fail Error is irrelevant to CV4PVE-Admin.  

1. SSH to Proxmox and type journalctl -f and see if there are Error Messages 
2. Are you using DHCP or Static IP Address for Proxmox.......if Static.....make sure to Reserve the IP Address from the DHCP Range 
    if that is where you got the IP Address from
4. **As FrankLupo stated.....Delete Browser Cache or Close the TAB and Open a New One**

**Comment by franklupo** [comment]
News?

**Comment by weili0677** [comment]
> @weili0677
> 
> The Proxmox Connect Fail Error is irrelevant to CV4PVE-Admin.
> 
> 1. SSH to Proxmox and type journalctl -f and see if there are Error Messages
> 2. Are you using DHCP or Static IP Address for Proxmox.......if Static.....make sure to Reserve the IP Address from the DHCP Range
>    if that is where you got the IP Address from
> 3. **As FrankLupo stated.....Delete Browser Cache or Close the TAB and Open a New One or Close Restart Effected Browser**
> 
> Setting your Proxmox Account to be the same as your Linux Root Account does not matter either.

It's not working.

**Comment by franklupo** [comment]
can you try to run it outside Proxmox VE in another host?

Also try the new aversion

bets regards

**Comment by kenrmayfield** [comment]
@weili0677 

Also what is the Exact Error Message?

**Comment by weili0677** [comment]
I update to 1.0.1 and it fix this bug.Thank you so much.

**Comment by weili0677** [comment]
the service was not fix.I will create new Issues.
