### ISSUE TITLE
Hello，I want know how to reset my password

### ISSUE THREAD

**Issue by Azhc** [Corsinvest/cv4pve-admin#79]
### Feature request type

Other

### Describe the solution you'd like

Hello, I have deployed cve-admin on Docker, but I have forgotten the login password and I haven't configured any email-related services. Could you please tell me how to reset the password within the Docker container?

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
Hi,
right now the fastest solution is to set the PasswordHash field to null in the Users table of the app.db in the data directory.
You can use sqlitestudio.

We will do a password reset procedure.

best regards

**Comment by MANKUD** [comment]
@franklupo 

Hello,

This is the first time I am trying to access the admin panel but its asking me to login without the initial setup process.

![image](https://github.com/Corsinvest/cv4pve-admin/assets/83474708/72b603c6-345b-446c-8b17-4fb60e8bb987)

**Comment by franklupo** [comment]
username: ***@***.*** password: Password123!

 

 

Da: MANKUD ***@***.***> 
Inviato: lunedì 7 agosto 2023 18:30
A: Corsinvest/cv4pve-admin ***@***.***>
Cc: Daniele Corsini ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Corsinvest/cv4pve-admin] Hello，I want know how to reset my password (Issue #79)

 

@franklupo <https://github.com/franklupo> 

Hello,

This is the first time I am trying to access the admin panel but its asking me to login without the initial setup process.

 <https://user-images.githubusercontent.com/83474708/258869340-72b603c6-345b-446c-8b17-4fb60e8bb987.png>

**Comment by MANKUD** [comment]
@franklupo thanks for your response I was able to login in but what seems to be happening now is that I am not able to add more than one server there seems to be a bug in the windows version that I tried.

**Comment by MANKUD** [comment]
![image](https://github.com/Corsinvest/cv4pve-admin/assets/83474708/605dfb3e-2d5b-4624-a640-b55a42651ec9)

**Comment by franklupo** [comment]
Hi,
which version of proxmox do you use in the other connections?

best regards

**Comment by MANKUD** [comment]
Hello,

The thing is that its able to add only one server and others are just shown blank as you can see in the previous screenshots.
The versions that I use are as  below
7.2-11
7.3-4
7.4-3

**Comment by franklupo** [comment]
Are the servers accessible on the network?

**Comment by MANKUD** [comment]
Hello,

Yes of course they are available publicly and I am able to add all three of them one at a time and when I try to add more than one only the first one is shown and the rest are blank as you can see above.

**Comment by MANKUD** [comment]
There is no error it saves it successfully.

**Comment by franklupo** [comment]
I found the problem, in the next version it will be fixed.

Best regards

**Comment by MANKUD** [comment]
when can we expect the next version 😄

**Comment by franklupo** [comment]
New releases available!

best regards
