### ISSUE TITLE
App Crash Randomnly on Windows Machine

### ISSUE THREAD

**Issue by MANKUD** [Corsinvest/cv4pve-admin#90]
### Bug type

Other

### What happened?

The App randomnly crashes on the window machine.

[logs.zip](https://github.com/Corsinvest/cv4pve-admin/files/12352395/logs.zip)

### Expected behavior

The App randomnly crashes on the window machine.

### Proxmox VE Version

7.x.x

### Version (bug)

1.0.1

### What browsers are you seeing the problem on?

Chrome

### On what operating system are you experiencing the issue?

Windows

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
HI,
if you execute docker have a same problem?

**Comment by MANKUD** [comment]
Hello,

I have not tried on docker and only windows version I have tried.

**Comment by franklupo** [comment]
The logs do not display any type of error.

Are there any errors in the shell when it stops?

**Comment by MANKUD** [comment]
Here is a screenshot.

![image](https://github.com/Corsinvest/cv4pve-admin/assets/83474708/bf02b4e7-819e-4243-8abe-51a57cdd3ac1)
