### ISSUE TITLE
Update GUI - english

### ISSUE THREAD

**Issue by silycr** [Corsinvest/cv4pve-admin#93]
### Feature request type

Enhance component

### Describe the solution you'd like

Update the wording on the GUI to better suit the applicable meaning.
For example: 

**Creating an Auto Snapshot, the toggle options of
    Vm Status = Include RAM
    Only Runs = While VM/CT Running

**Menu>>Safe>>Node Protect
    Schedulation not active! = [Scheduling / Schedule] not active!

**Menu>>Utilities>>Free Memory Node
    Free Memory Node = Memory Cleanup

I'll add more as I pick them up.

**Comment by jpSimkins** [comment]
**Safe> >Auto Snapshot
Clean  = Purge Snapshots

This one got me as I thought this would remove any snapshots that were left behind over my Keep setting.

**Comment by franklupo** [comment]
Fix in next release
