### ISSUE TITLE
User creation password system only works when entering password, making password manager useless

### ISSUE THREAD

**Issue by jpSimkins** [Corsinvest/cv4pve-admin#94]
### Bug type

Other

### What happened?

I created a new user (in cv4pve-admin), when I got to the password, I copied in a 42 character random password generated by 1Password. When I tried to create the user, it get:

> PasswordTooShort - Passwords must be at least 6 characters. PasswordRequiresUniqueChars - Passwords must use at least 1 different characters.

This is the password used: `!eHP2peChN6ysjs4RtD-KybhE9zH89HD-ddmpP_Tb.`

When creating a new user, you MUST enter the password by hand or add a space to the end then delete it for the password to be accepted. This is not a standard way to check password length.

I experience the same issue (no error, just won't let you change the password) when changing the password from the user list option.

### Expected behavior

I expected to be able to paste the password in and it work

### Relevant log output

```shell
PasswordTooShort - Passwords must be at least 6 characters. PasswordRequiresUniqueChars - Passwords must use at least 1 different characters.
```

### Proxmox VE Version

8.0.4

### Version (bug)

1.0.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Other

### On what operating system are you experiencing the issue?

Windows, Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by franklupo** [comment]
Hi,
I found the problem.
Fix in next release.

best regards
