### ISSUE TITLE
Health Check is giving false flags

### ISSUE THREAD

**Issue by jpSimkins** [Corsinvest/cv4pve-admin#95]
### Bug type

Component

### Component name

Health -> Diagnostic

### What happened?

Hello, 

I recently found this and am starting to play around with it to understand how useful it can be. I appreciate your hard work.

I found some issues that I wanted to bring to your attention.

I ran a health check under `Health -> Diagnostic`. When I looked at the PDF that was generated, I noticed many minor issues that were incorrect.

False Flags:
- cv4pve-autosnap is not configured. 
    - It is and it is running just fine. I even tested a recovery with them.
- Service 'syslog.service' not running
    - Proxmox 8 uses journald so this is not applicable
- Disk '/dev/sda' S.M.A.R.T. status problem
    - This one is a bit tricky. I have a hardware RAID that is on a Dell server so it is using megaraid. This may be a Proxmox issue and I haven't identified this yet but I use other tools for SMART. So I should probably just ignore this one.
-  Disk ssd '/dev/sda' wearout not valid.
    - May be related to the above SMART issue.    
-  Image Orphaned 4 MB file vm-100-disk-2
    - I have this for every TPM disk. These are not orphaned and are used. I have 5 VMs using TPM so all 5 give this error.

One more thing to note, the PDF is 2 pages but only 1 page was enough. The second page is empty with just header and footer. Not an issue really, just an FYI.

### Expected behavior

While the SMART issues I expected, the other issues I did not. 

While the report is useful, with the false flags, this is not something I would run again until further updates are provided. 

### Proxmox VE Version

8.1.3

### Version (bug)

8.1.3

### What browsers are you seeing the problem on?

Firefox, Chrome

### On what operating system are you experiencing the issue?

Windows, Linux

### Pull Request

- [ ] I would like to do a Pull Request

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpSimkins** [comment]
An update for the false flag for: `cv4pve-autosnap is not configured`

This was due to no snapshots being created when the test ran. I accidentally clicked `Clean` not realized it is a purge of snapshots. Then I ran the health check. Perhaps rename that to Purge Snapshots? I wasn't sure what that was and assumed it would just remove any over the threshold. 

I singe manually triggered the autosnapshot task and re-ran the health check and it is gone.

My tests of the snapshots were before the health check and before I clicked on `Clean`. 

I will still leave this as a false flag as even though there were no snapshots, the autosnap was configured and scheduled. Perhaps it's a translation issue but I would expect that to not show even if no snapshots are created as it is configured.

**Comment by franklupo** [comment]
For **cv4pve-autosnap is not configured.** I check if there are autosnaps. If you do not present notice.

For **Disk '/dev/sda' S.M.A.R.T. status problem** and **Disk '/dev/sda' S.M.A.R.T. status problem** i test the values and if they aren't there it's an error. It could be a false positive but it can be added to the issues not to be checked.

For **Image Orphaned 4 MB file vm-100-disk-2** fixed in next release. Corsinvest/cv4pve-diag#5

For **Service 'syslog.service' not running** I check the services are active, if I don't report an error. You can disable issue control.

Best regards

**Comment by franklupo** [comment]
For **cv4pve-autosnap is not configured.** fixed in next release.

best regards
